server:
    port: 8085


###
#   Database Settings
###
spring:
  datasource:
    url: jdbc:h2:mem:craft_demo_db;DB_CLOSE_DELAY=-1
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
    sql-script-encoding: UTF-8
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  main:
        banner-mode: "off"

###
#   H2 Settings
###
  h2:
    console:
      enabled: true
      path: /console